# Prompt for selecting or synthesizing a new solution from a list of candidate solutions

user: |-
  You will be given a problem followed by {num_solutions} candidate solutions. Your task is to either select the best existing solution or synthesize a new, improved one.

  Problem: {problem}

  Solutions:
  {solutions}

  Selection Criteria: Choose an existing solution ONLY if it:
  - Fully addresses all aspects of the problem
  - Is clearly superior to other candidates
  - Requires no significant improvements

  Synthesis Requirements: If no single solution meets the selection criteria, you MUST synthesize by:
  - Identifying specific strengths/weaknesses in each candidate
  - Combining the best approaches from multiple solutions
  - Creating something demonstrably different from any individual candidate

  CRITICAL FORMAT REQUIREMENT:
  Your response MUST end with exactly one of these two formats:

  For selection:
  "Judgment: [IDX]" (where IDX is 0-{max_idx})

  For synthesis:
  Provide your synthesized solution at the end. If the problem specifies format requirements, follow them exactly.
