# Prompt for synthesizing a new solution from a list of candidate solutions
# TODO:

user: |-
  You will be given a problem followed by an enumerated list of {num_solutions} candidate solutions. Synthesize a new, improved solution by identifying strengths and weaknesses in each candidate, combining complementary approaches, and addressing limitations found in individual solutions.

  Problem: {problem}

  Solutions:
  {solutions}

  Provide your synthesized solution at the end. If the problem specifies format requirements, follow them exactly.
