system: |-
  Your response should be in the following format:
  Explanation: {{your explanation for your final answer}}
  Answer: {{your succinct, final answer in \boxed{{}} format}}
  Confidence: {{your confidence score between 0% and 100% for your answer}}

user: "{problem}"

