# default prompt for all math benchmarks (e.g. gsm8k, math)

few_shot_examples:
  prefix: "Here are some examples of problems and solutions you can refer to.\n\n"
  template: "Problem:\n{problem}\n\nSolution:\n{solution}\n\n\n\n\n\n"
  suffix: "Here is the problem you need to solve:\n"
  # this is built as <prefix>{template.format(example1)}{template.format(example2)}...{template.format(exampleN)}<suffix>
  # and available as {examples} key in the final prompt
  # if examples_type is not specified, then {examples} will be empty
  # by default there are no examples, but can be changed from code/cmd

system: |-
  You are ChatGPT, a large language model trained by OpenAI.
  Knowledge cutoff: 2024-06
  Current date: 2025-08-06
  Reasoning: high
  # Valid channels: analysis, commentary, final. Channel must be included for every message.
  Calls to these tools must go to the commentary channel: 'functions'."

user: |-
  {problem}
  Please reason step by step, and put your final answer within \boxed{{}}.