pipeline:
  cluster: slurm
  output_dir: /scratch/fsw/portfolios/llmservice/users/yachen/AceMath/Skills/aceproof-tts-output
  input_paths: /scratch/fsw/portfolios/llmservice/users/yachen/AceMath/Skills/recipes/aceproof/DeepSeek-Math-V2/IMO2025.json
  partition: batch
  cpu_partition: cpu
  data_job_gpus: 0
  data_job_partition: null
  start_round: 1
  max_rounds: 16
  dependent_jobs: 0
  proof_gen_dependent_jobs: 0
  refine_dependent_jobs: 0
  verify_dependent_jobs: 0
  rerun_done: false

scaling:
  n_parallel_proof_gen: 128
  n_verification_per_proof: 64
  n_agg_trials: 32
  n_best_proofs_to_sample: 32
  n_proofs_to_refine: 1
  max_rating_per_score: 4
  solved_threshold: 0.99999
  proof_gen_chunks: 1
  proof_refine_chunks: 1
  verification_chunks: 16

inference:
  proof_gen:
    tokens_to_generate: 120000
    temperature: 1.0
    top_p: 0.95
    max_concurrent_requests: 1024
  proof_refine:
    tokens_to_generate: 120000
    temperature: 1.0
    top_p: 0.95
    max_concurrent_requests: 1024
  verification:
    tokens_to_generate: 64000
    temperature: 1.0
    top_p: 0.95
    max_concurrent_requests: 1024

model_profile: deepseek_v32
model_profile_by_stage:
  proof_gen: deepseek_v32
  verify: deepseek_v32
  refine: deepseek_v32
model_profiles:
  deepseek_v32:
    model: /scratch/fsw/portfolios/llmservice/users/yachen/cache/DeepSeek-V3.2-Speciale
    server_type: sglang
    server_gpus: 8
    server_nodes: 1
    server_container: /scratch/fsw/portfolios/llmservice/users/yachen/AceMath/container/nemo-skills-sglang-v32.sqsh
    server_args: "--ep-size 8 --dp 8 --enable-dp-attention --reasoning-parser deepseek-v3 --log-requests --mem-fraction-static=0.8"
    server_address: null
    inline_args: "++inference.endpoint_type=chat ++chat_template_kwargs.thinking=true"
    system_prompt: null
    system_prompt_path: null
  nano_v3:
    model: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16
    server_type: vllm
    server_gpus: 1
    server_nodes: 1
    server_container: null
    server_args: "--mamba_ssm_cache_dtype float32 --no-enable-prefix-caching"
    server_address: null
    inline_args: ""
    system_prompt: null
    system_prompt_path: null
