pipeline:
  cluster: aws-dfw2
  output_dir: /workspace/aceproof-tts/ultra-fp8/gems-remarkable-smoke1-r1-quote2
  input_paths: /nemo_run/code/nemo_skills/dataset/gems-remarkable/test_sample1.jsonl
  partition: batch
  qos: normal
  cpu_partition: cpu
  data_qos: null
  data_job_gpus: 0
  data_job_partition: cpu
  start_round: 1
  max_rounds: 1
  dependent_jobs: 0
  proof_gen_dependent_jobs: 0
  refine_dependent_jobs: 0
  verify_dependent_jobs: 0
  rerun_done: false
  sbatch_kwargs:
    segment: 4
  data_sbatch_kwargs: {}

scaling:
  n_parallel_proof_gen: 128
  n_verification_per_proof: 64
  n_agg_trials: 32
  n_best_proofs_to_sample: 32
  n_proofs_to_refine: 1
  max_rating_per_score: 4
  solved_threshold: 0.99999
  proof_gen_chunks: 1
  proof_refine_chunks: 1
  verification_chunks: 1

inference:
  proof_gen:
    tokens_to_generate: 120000
    temperature: 1.0
    top_p: 0.95
    max_concurrent_requests: 1024
  proof_refine:
    tokens_to_generate: 120000
    temperature: 1.0
    top_p: 0.95
    max_concurrent_requests: 1024
  verification:
    tokens_to_generate: 64000
    temperature: 1.0
    top_p: 0.95
    max_concurrent_requests: 1024

model_profile: ultra_fp8
model_profile_by_stage:
  proof_gen: ultra_fp8
  verify: ultra_fp8
  refine: ultra_fp8
model_profiles:
  ultra_fp8:
    model: /lustre/fsw/portfolios/llmservice/users/igitman/ultra-models/sft-16000-fp8
    server_type: vllm
    server_gpus: 4
    server_nodes: 4
    server_container: /lustre/fsw/portfolios/llmservice/users/igitman/super-models/vllm-hsg-03-16.sqsh
    server_args: >-
      --trust-remote-code
      --load-format auto
      --tensor-parallel-size 4
      --data-parallel-size 4
      --data-parallel-backend ray
      --data-parallel-address $(getent hosts $SLURM_MASTER_NODE | awk '{print $1}')
      --data-parallel-size-local 1
      --distributed-executor-backend ray
      --enable-expert-parallel
      --kv-cache-dtype auto
      --gpu-memory-utilization 0.85
      --max-num-seqs 128
      --max-cudagraph-capture-size 128
      --max-num-batched-tokens 8480
      --max-model-len 262144
      --mamba-cache-mode align
      --enable-prefix-caching
      --enable-chunked-prefill
      --reasoning-parser-plugin /lustre/fsw/portfolios/llmservice/users/igitman/ultra-models/reasoning_parser.py
      --reasoning-parser ultra_v3
      --model-loader-extra-config '{\"enable_multithread_load\":true,\"num_threads\":96}'
    server_address: null
    inline_args: ""
    system_prompt: null
    system_prompt_path: null
