gpqa: 
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/1.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/2.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/3.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/4.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/5.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/6.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/7.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/8.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/9.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/10.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/11.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/12.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/13.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/14.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/15.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/16.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/17.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/18.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/19.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/20.yaml
  - nemo_skills/prompt/config/eval/mcq_prompts_v0/21.yaml


comp-math-24-25:
  - nemo_skills/prompt/config/eval/math_prompts_v0/1.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/2.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/3.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/4.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/5.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/6.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/7.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/8.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/9.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/10.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/11.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/12.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/13.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/14.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/15.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/16.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/17.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/18.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/19.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/20.yaml
  - nemo_skills/prompt/config/eval/math_prompts_v0/21.yaml