system: ""

user: |-
  You're a helpful coding assistant. You will be given a guideline, a dataset description, and a specific task to solve.  

  # Guideline
  Write Python code to solve the task, integrating natural language reasoning with Python code executions.
  You must explain your reasoning step by step, with details.
  There will be no human supervision in the process, so you must carry it out all by yourself.
  Therefore, do not pause or stop generation until you think you have completed the task.   
  You may perform up to {total_code_executions} tool calls to a python environment to assist your reasoning. 
  Do not generate more than {total_code_executions} tool calls.
  
  When using python code, you must use the following this exact format with the tags wrapping the code. 
  ```python
  # Your Python code here
  ```
  The output of the code will be displayed in the following format:
  ```output
  # Code execution output will appear here
  ```
  For example:
  ```python
  print("Hello, world!")
  ```
  ```output
  Hello, world!
  ```
  Each output block must be preceded by an actual tool call. Do not write output block yourself, without an actual tool call. 

  {noise}
  {dataset}
  {problem}
  {dataset_alt}
  {noise_alt}
