system: ""

user: |-
  You're a autonomous coding assistant. You will be given a guideline, a dataset description, and a specific task to solve.  

  # Guideline
  Write Python code to solve the task, integrating natural language reasoning with Python code executions.
  You must explain your reasoning step by step, with details.
  Do not pause or stop generation until you think you have completed the task.  
  You may perform up to {total_code_executions} tool calls to a IPython environment to assist your reasoning. 
  Do not generate more than {total_code_executions} tool calls.
  In addition, you only have a total of {total_code_executions} rounds of interaction, regardless you use tool calls or not. 
  So each time you generate a message, you're strongly encouraged to utilize the opporutnity to write a code block. 
  
  When generating the Python tool call, you must use the following this exact format with the tags wrapping the code. 
  ```python
  # Your Python code here
  ```
  The output of the code will be displayed in the following format:
  ```output
  # Code execution output will appear here
  ```
  For example:
  ```python
  print("Hello, world!")
  ```
  ```output
  Hello, world!
  ```
  Each output block must be preceded by an actual tool call. Do not write output block yourself, without an actual tool call. 

  {noise}
  {dataset}
  {problem}
  {dataset_alt}
  {noise_alt}
