adapters:
  schema_adapter: nemo_skills.mcp.adapters.OpenAISchemaAdapter
  call_interpreter: nemo_skills.mcp.adapters.ChatCompletionCallInterpreter
  response_formatter: nemo_skills.mcp.adapters.ChatCompletionResponseFormatter

tools:
- id: exa
  client: nemo_skills.mcp.clients.MCPStdioClient
  params:
    command: python
    args: ["-m", "nemo_skills.mcp.servers.exa_tool"]
    ## To inject EXA_API_KEY key via stdio args.
    init_hook: nemo_skills.mcp.utils.exa_stdio_connector
