#!/usr/bin/env python3
# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Real SFT K8s Pipeline Run
#
# Calls _run_sft_kubernetes() from the login node to submit a real
# training job to Kubernetes via the Pipeline + KubernetesBackend
# code path. This proves the actual NeMo-Skills K8s pipeline works
# end-to-end, not just imports.
#
# What this exercises:
#   1. _run_sft_kubernetes() constructs a Pipeline with training + conversion jobs
#   2. Pipeline._run_kubernetes() converts CommandGroups to JobSpecs
#   3. KubernetesBackend.submit_job() creates Headless Service + Indexed Job
#   4. KubernetesBackend._inject_distributed_env_vars() sets MASTER_ADDR etc.
#   5. The job runs torchrun with the training command inside the container
#
# Usage (from login node with kubectl access):
#   cd ~/nemo-skills/Skills
#   PYTHONPATH=. .venv/bin/python scripts/k8s-tests/run_sft_k8s_real.py
#   PYTHONPATH=. .venv/bin/python scripts/k8s-tests/run_sft_k8s_real.py --num-nodes 2 --num-gpus 2

"""Submit and monitor a real SFT job through Pipeline + KubernetesBackend."""

import argparse
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


def main():
    """Build a minimal real SFT pipeline, submit it, and stream job logs."""
    parser = argparse.ArgumentParser(description="Real SFT K8s Pipeline Run")
    parser.add_argument("--num-gpus", type=int, default=2)
    parser.add_argument("--num-nodes", type=int, default=1)
    parser.add_argument("--namespace", default="default")
    parser.add_argument("--image", default=os.environ.get("SFT_IMAGE", "nemo-skills/nemo-rl:latest"))
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    print("================================================================")
    print("Real SFT K8s Pipeline Run")
    print("================================================================")
    print(f"  Nodes:     {args.num_nodes}")
    print(f"  GPUs/node: {args.num_gpus}")
    print(f"  Namespace: {args.namespace}")
    print(f"  Image:     {args.image}")
    print(f"  Dry run:   {args.dry_run}")
    print("================================================================")

    # The training command — GPT-2 SFT with HuggingFace Trainer
    # This is what would normally be generated by NemoRLTask.get_cmd()
    train_cmd = (
        "pip install -q accelerate && "
        "export NCCL_DEBUG=INFO && "
        f"torchrun --nproc_per_node={args.num_gpus} --nnodes={args.num_nodes} "
        f"--node_rank=${{NODE_RANK:-0}} --master_addr=${{MASTER_ADDR:-localhost}} "
        f"--master_port=29500 /opt/NeMo-Skills/scripts/k8s-tests/sft_train_pipeline.py"
    )

    cluster_config = {
        "executor": "kubernetes",
        "namespace": args.namespace,
        "containers": {"nemo-rl": args.image},
        "skip_hf_home_check": True,
        "default_timeout": "00:30:00",
        "image_pull_policy": "Never",  # Image loaded locally via ctr import
    }

    print("\nBuilding Pipeline via NeMo-Skills declarative API...")
    print("  Pipeline -> _convert_groups_to_job_spec -> KubernetesBackend.submit_job")

    import nemo_run as run

    from nemo_skills.pipeline.utils.declarative import (
        Command,
        CommandGroup,
        HardwareConfig,
        Pipeline,
    )

    script = run.Script(inline=train_cmd)
    command = Command(script=script, container="nemo-rl", name="sft-trainer")
    group = CommandGroup(
        commands=[command],
        hardware=HardwareConfig(
            num_gpus=args.num_gpus,
            num_nodes=args.num_nodes,
        ),
        name="real-sft-pipeline",
        log_dir="/tmp/sft-logs",
    )

    pipeline = Pipeline(
        name="real-sft-pipeline",
        cluster_config=cluster_config,
        jobs=[{"name": "sft-train", "group": group}],
        skip_hf_home_check=True,
    )

    result = pipeline.run(dry_run=args.dry_run)

    if args.dry_run:
        print("\nDry run complete — Pipeline was constructed but not submitted.")
        return

    if result is None:
        print("\nPipeline returned None (unexpected)")
        sys.exit(1)

    # result is a dict of {job_name: JobHandle}
    print(f"\nSubmitted {len(result)} job(s) via Pipeline + KubernetesBackend:")
    for name, handle in result.items():
        print(f"  {name}: job_id={handle.job_id}")
        svc = handle.metadata.get("headless_service")
        if svc:
            print(f"    headless_service={svc}")

    # Wait for completion and get logs
    from nemo_skills.pipeline.backends import JobStatus, get_backend

    backend = get_backend(cluster_config)

    for name, handle in result.items():
        print(f"\nWaiting for job '{name}'...")
        status = backend.wait_for_completion(handle, timeout=900)
        print(f"Status: {status.value}")

        print("\n--- Logs ---")
        for line in backend.get_logs(handle):
            print(line, end="" if line.endswith("\n") else "\n")

        # Cleanup
        backend.cleanup(handle)

        if status != JobStatus.SUCCEEDED:
            print(f"\nFAILED: {name} (status={status.value})")
            sys.exit(1)

    print("\n================================================================")
    print("REAL SFT K8S PIPELINE: ALL JOBS COMPLETED")
    print("================================================================")


if __name__ == "__main__":
    main()
