# default prompt for codeelo c++

system: ""

user: |-
  You are a coding expert. Given a competition-level coding problem, you need to write a C++ program to solve it. 
  You may start by outlining your thought process. In the end, please provide the complete code in a code block enclosed with ```cpp ```.
  
  {question}
