#!/usr/bin/env python3
"""Extract decomposition-planner outputs into subproblem-solver inputs."""

from __future__ import annotations

import argparse
import glob
import hashlib
import json
import re
from pathlib import Path
from typing import Any

SUB_RE = re.compile(
    r"(?ms)^###\s+Subproblem\s+(\d+)\s*\n(.*?)(?=^###\s+Subproblem\s+\d+\s*\n|^##\s+Self Evaluation|\Z)"
)


def _iter_jsonl(patterns: list[str]):
    for pattern in patterns:
        for file_path in sorted(glob.glob(pattern)):
            with open(file_path, encoding="utf-8") as fin:
                for line in fin:
                    if not line.strip():
                        continue
                    row = json.loads(line)
                    row["_source_file"] = file_path
                    yield row


def _load_originals(path: str) -> dict[str, str]:
    originals: dict[str, str] = {}
    with open(path, encoding="utf-8") as fin:
        for line in fin:
            if not line.strip():
                continue
            row = json.loads(line)
            question = row.get("original_problem") or row.get("problem") or row.get("question") or ""
            originals[row.get("problem_idx")] = question
    return originals


def _uid(row: dict[str, Any], text: str) -> str:
    seed = row.get("generation_seed", row.get("row_id", "noseed"))
    digest = hashlib.sha1(text.encode("utf-8")).hexdigest()[:12]
    return f"{row.get('problem_idx')}:{seed}:{digest}"


def build(args) -> None:
    originals = _load_originals(args.base_input)
    rows = []
    planner_count = 0
    for row in _iter_jsonl(args.planner_glob):
        if not row.get("valid", True):
            continue
        problem_idx = row.get("problem_idx")
        if problem_idx not in originals:
            continue
        planner_text = str(row.get("proof") or row.get("generation") or "").strip()
        if not planner_text:
            continue
        planner_count += 1
        planner_uid = _uid(row, planner_text)
        matches = list(SUB_RE.finditer(planner_text))[: args.max_subproblems_per_plan]
        for match in matches:
            sub_idx = int(match.group(1))
            sub_text = match.group(2).strip()
            question = "\n".join(
                [
                    "## Original Problem",
                    originals[problem_idx],
                    "",
                    "## Generated Decomposition Context",
                    (
                        "The following subproblem was generated by a model planner. It is not trusted; "
                        "prove it from the original problem or identify why it is false/too strong."
                    ),
                    "",
                    f"planner_uid: {planner_uid}",
                    f"subproblem_index: {sub_idx}",
                    "",
                    "## Subproblem To Solve",
                    sub_text,
                ]
            )
            out = {
                "problem_idx": problem_idx,
                "source_name": args.source_name,
                "question": question,
                "original_problem": originals[problem_idx],
                "planner_uid": planner_uid,
                "planner_source_file": row.get("_source_file"),
                "planner_generation_seed": row.get("generation_seed"),
                "subproblem_index": sub_idx,
                "subproblem_text": sub_text,
            }
            rows.append(out)
    if args.max_rows_per_problem > 0:
        by_problem: dict[str, list[dict[str, Any]]] = {}
        for row in rows:
            by_problem.setdefault(row["problem_idx"], []).append(row)
        rows = []
        for problem_idx in sorted(by_problem):
            rows.extend(by_problem[problem_idx][: args.max_rows_per_problem])
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8") as fout:
        for row in rows:
            fout.write(json.dumps(row, ensure_ascii=False) + "\n")
    print(f"planner_rows={planner_count}")
    print(f"subproblem_rows={len(rows)} -> {output}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base_input", required=True)
    parser.add_argument("--planner_glob", action="append", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--source_name", default="repeat10_decomposition_subproblems")
    parser.add_argument("--max_subproblems_per_plan", type=int, default=5)
    parser.add_argument("--max_rows_per_problem", type=int, default=128)
    build(parser.parse_args())


if __name__ == "__main__":
    main()
