#!/usr/bin/env python3
"""Build proof-generation inputs from model-generated attempt-memory notes."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def _load_base(path: str, targets: set[str] | None) -> dict[str, dict]:
    rows: dict[str, dict] = {}
    with open(path, encoding="utf-8") as fin:
        for line in fin:
            if not line.strip():
                continue
            row = json.loads(line)
            problem_idx = row.get("problem_idx")
            if targets and problem_idx not in targets:
                continue
            rows[problem_idx] = row
    return rows


def _load_memory(path: str) -> dict[str, dict]:
    rows: dict[str, dict] = {}
    with open(path, encoding="utf-8") as fin:
        for line in fin:
            if not line.strip():
                continue
            row = json.loads(line)
            if not row.get("valid", True):
                continue
            problem_idx = row.get("problem_idx")
            memory = str(row.get("proof") or row.get("generation") or "").strip()
            if not problem_idx or not memory:
                continue
            rows.setdefault(problem_idx, row)
    return rows


def build(args) -> None:
    targets = set(args.target_problem or []) or None
    base_rows = _load_base(args.base_input, targets)
    memory_rows = _load_memory(args.memory_output)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    wrote = 0
    missing: list[str] = []
    with output.open("w", encoding="utf-8") as fout:
        for problem_idx, base in base_rows.items():
            mem = memory_rows.get(problem_idx)
            if mem is None:
                missing.append(problem_idx)
                continue
            original = base.get("question") or base.get("problem") or base.get("original_problem") or ""
            memory = str(mem.get("proof") or mem.get("generation") or "").strip()
            question = "\n".join(
                [
                    "## Original Problem",
                    original,
                    "",
                    "## Model-Generated Attempt Memory",
                    (
                        "The following note was generated by the same proof model from previous model attempts "
                        "and verifier comments. It is not a trusted source; reprove every idea before using it."
                    ),
                    "",
                    memory,
                ]
            )
            out_row = dict(base)
            out_row["source_name"] = args.source_name
            out_row["question"] = question
            out_row["attempt_memory_source_file"] = args.memory_output
            out_row["attempt_memory_seed"] = mem.get("generation_seed")
            fout.write(json.dumps(out_row, ensure_ascii=False) + "\n")
            wrote += 1
    print(f"base_problems={len(base_rows)}")
    print(f"memory_rows={len(memory_rows)}")
    print(f"written={wrote} -> {output}")
    if missing:
        print("missing_memory=" + ",".join(missing))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base_input", required=True)
    parser.add_argument("--memory_output", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--target_problem", action="append")
    parser.add_argument("--source_name", default="repeat10_with_model_attempt_memory")
    build(parser.parse_args())


if __name__ == "__main__":
    main()
