#!/usr/bin/env python3
"""Build final assembly inputs from decomposition plans and subproblem attempts."""

from __future__ import annotations

import argparse
import glob
import hashlib
import json
from collections import defaultdict
from pathlib import Path
from typing import Any


def _iter_jsonl(patterns: list[str]):
    for pattern in patterns:
        for file_path in sorted(glob.glob(pattern)):
            with open(file_path, encoding="utf-8") as fin:
                for line in fin:
                    if not line.strip():
                        continue
                    row = json.loads(line)
                    row["_source_file"] = file_path
                    yield row


def _load_originals(path: str) -> dict[str, str]:
    originals: dict[str, str] = {}
    with open(path, encoding="utf-8") as fin:
        for line in fin:
            if not line.strip():
                continue
            row = json.loads(line)
            originals[row.get("problem_idx")] = (
                row.get("original_problem") or row.get("problem") or row.get("question") or ""
            )
    return originals


def _shorten(text: str, limit: int) -> str:
    text = str(text or "").strip()
    if len(text) <= limit:
        return text
    return text[:limit].rstrip() + "\n...[truncated]"


def _proof_key(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8")).hexdigest()[:12]


def build(args) -> None:
    originals = _load_originals(args.base_input)
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in _iter_jsonl(args.subproblem_glob):
        if not row.get("valid", True):
            continue
        problem_idx = row.get("problem_idx")
        if problem_idx not in originals:
            continue
        proof = str(row.get("proof") or row.get("generation") or "").strip()
        if not proof:
            continue
        grouped[problem_idx].append(row)

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    wrote = 0
    with output.open("w", encoding="utf-8") as fout:
        for problem_idx in sorted(originals):
            rows = grouped.get(problem_idx, [])
            rows.sort(
                key=lambda r: (
                    float(r.get("self_eval_score") or 0),
                    len(str(r.get("proof") or "")),
                ),
                reverse=True,
            )
            rows = rows[: args.max_subproblem_attempts]
            if not rows:
                continue
            parts = [
                "## Original Problem",
                originals[problem_idx],
                "",
                "## Generated Subproblem Material",
                (
                    "The following subproblems and subproblem proof attempts were generated by the model. "
                    "They are not trusted; before using any statement, check or reprove it in the final solution."
                ),
            ]
            for idx, row in enumerate(rows, 1):
                proof = str(row.get("proof") or row.get("generation") or "").strip()
                parts.extend(
                    [
                        "",
                        f"### Subproblem Attempt {idx}",
                        f"planner_uid: {row.get('planner_uid')}",
                        f"subproblem_index: {row.get('subproblem_index')}",
                        f"attempt_key: {_proof_key(proof)}",
                        f"self_eval_score: {row.get('self_eval_score')}",
                        "",
                        "Subproblem statement:",
                        _shorten(row.get("subproblem_text") or "", args.max_subproblem_chars),
                        "",
                        "Subproblem proof attempt:",
                        _shorten(proof, args.max_proof_chars),
                    ]
                )
            base = {
                "problem_idx": problem_idx,
                "source_name": args.source_name,
                "question": "\n".join(parts),
                "original_problem": originals[problem_idx],
            }
            fout.write(json.dumps(base, ensure_ascii=False) + "\n")
            wrote += 1
    print(f"problems_with_subproblem_attempts={len(grouped)}")
    print(f"written={wrote} -> {output}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base_input", required=True)
    parser.add_argument("--subproblem_glob", action="append", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--source_name", default="repeat10_decomposition_assembly")
    parser.add_argument("--max_subproblem_attempts", type=int, default=24)
    parser.add_argument("--max_subproblem_chars", type=int, default=2500)
    parser.add_argument("--max_proof_chars", type=int, default=10000)
    build(parser.parse_args())


if __name__ == "__main__":
    main()
