name: Build Dockerfile.nemo-gym

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'dockerfiles/Dockerfile.nemo-gym'
      - '.github/workflows/dockerfile_nemo_gym.yml'

  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Free up disk space on Ubuntu
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Build Dockerfile.nemo-gym
      run: |
        REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker buildx build \
          --file dockerfiles/Dockerfile.nemo-gym \
          --cache-from type=registry,ref=ghcr.io/${REPO_LOWER}/nemo-gym-image:cache \
          --cache-to type=registry,ref=ghcr.io/${REPO_LOWER}/nemo-gym-image:cache,mode=min \
          dockerfiles/
